mybatis:
#  type-aliases-package: com.arno.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
        com.arno.blog.mapper: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: blog
    password: blogDcba@4321
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 192.168.56.101
      database: blog

upload:
  base-url: http://localhost/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg